In [1]:
import re
text = "Machine learning rocks! Visit http://example.com for 1,234 updates in 2023."
cleaned = re.sub(r"http\S+|\d+|[,!.]", "", text.lower())
print(cleaned)

machine learning rocks visit  for  updates in 


In [2]:
import numpy as np
a = np.arange(22,71,2)
a

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_rel

def analyze_ratings(seed_value):
    """
    Analyzes restaurant ratings to determine if there is a significant increase post-revamp.

    Return:
        - Mean difference between ratings (rounded to 3 decimals).
        - p-value from hypothesis test (rounded to 2 decimals).
        - Conclusion: "Significant Increase" if p < 0.05, else "No Significant Increase".
    """

    # Step 1: Generate synthetic data (Ratings for 30 customers)
    np.random.seed(seed_value)
    before_ratings = np.random.uniform(2.5, 4.5, 30)  # Ratings before menu revamp
    after_ratings = before_ratings + np.random.uniform(0, 1, 30)  # Ratings after revamp

    # Step 2: Create a Pandas DataFrame
    df = pd.DataFrame({
        "Rating_Before": before_ratings,
        "Rating_After": after_ratings
    })

    # Step 3: Compute the mean rating difference using NumPy
    mean_difference=round(np.mean(df.iloc[:,0])-np.mean(df.iloc[:,1]),3)

    # Step 4: Perform a paired t-test using scipy.stats.ttest_rel
    p_value = round(ttest_rel(df["Rating_Before"],df["Rating_After"]).pvalue, 2)

    # Step 5: Determine conclusion based on hypothesis test result
    conclusion = "Significant Increase" if p_value < 0.05 else  "No Significant Increase"

    # return the results as required
    return mean_difference, p_value, conclusion
analyze_ratings(42)

(np.float64(-0.496), np.float64(0.0), 'Significant Increase')

In [ ]:
import pandas as pd
df=pd.read_csv("Ecommerce_Purchases.txt")
df["Year"]=df["CC Exp Date"].apply(lambda x: int(x.split("/")[1]))
df2=df["Year"][df["Year"]==25]
print(df2.count())

FileNotFoundError: [Errno 2] No such file or directory: 'Ecommerce_Purchases.txt'

In [ ]:
# @title Default title text
a = np.arange(10,22).reshape((3, 4))
print(a)

In [ ]:
p+q

In [ ]:
b = 3

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]])

In [ ]:
arr

In [ ]:
row_arr = arr[1:4, :]

In [ ]:
row_arr

In [ ]:
col_arr = row_arr[:, -3:]

In [ ]:
col_arr

# Food Delivery Data Exploration and analysis 1

---



![Highest Rated Restaurants](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/467/original/highest-rated_restaurants.png?1734428912)

![Average Cost for Two People](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/468/original/average_cost_for_two_people.png?1734428927)

![Votes and Ratings](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/469/original/votes_and_ratings.png?1734428939)

In [ ]:
import numpy as np

In [ ]:
int("4")

4

In [ ]:
l=[1,2,3,4]

In [ ]:
np.array([1,2,"sd"])

array(['1', '2', 'sd'], dtype='<U21')

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
votes = np.array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
  costs = np.array(["'800.0'" ,"'800.0'", "'800.0'", "'300.0'", "'600.0'", "'600.0'", "'600.0'", "'700.0'" ,"'550.0'", "'500.0'"])


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
import time
import numpy as np

In [ ]:
large_list = list(range(100000000))


In [ ]:
large_array = np.array(large_list)

In [ ]:
start = time.time()
sum_list = sum(large_list)
end = time.time()
list_time = end - start

In [ ]:
list_time

1.6405694484710693

In [ ]:
start = time.time()
sum_array = np.sum(large_array)
end = time.time()
array_time = end - start

In [ ]:
array_time

0.10147523880004883

In [ ]:
votes

array([ 775,  787,  918,   88,  166,  286, 2556,  324,  504,  402])

In [ ]:
votes *5

array([ 3875,  3935,  4590,   440,   830,  1430, 12780,  1620,  2520,
        2010])

In [ ]:
votes *20

array([15500, 15740, 18360,  1760,  3320,  5720, 51120,  6480, 10080,
        8040])

In [ ]:
votes.shape

(10,)

In [ ]:
votes.ndim

1

In [ ]:
subset_votes = votes
subset_costs = costs

In [ ]:
t = np.array([subset_votes, subset_costs]).T


In [ ]:
t

array([['775', "'800.0'"],
       ['787', "'800.0'"],
       ['918', "'800.0'"],
       ['88', "'300.0'"],
       ['166', "'600.0'"],
       ['286', "'600.0'"],
       ['2556', "'600.0'"],
       ['324', "'700.0'"],
       ['504', "'550.0'"],
       ['402', "'500.0'"]], dtype='<U21')

In [ ]:
t.shape

(10, 2)

In [ ]:
t.ndim

2

In [ ]:
t.size

20

In [ ]:
range(5)

range(0, 5)

In [ ]:
range(1,5)

range(1, 5)

In [ ]:
np.arange(1,15,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5])

In [ ]:
costs.dtype

dtype('<U7')

In [ ]:
a = [[1,100],
[2,200],
[3,300],
[4,400]]

In [ ]:
import numpy as np
arr = [80, 90, 10, 30, 40]
x = np.array(arr)
mask = (x < 80) & (x < 45)
mask
x[(x<80) & (x>=60)]

array([], dtype=int64)

In [ ]:
arr = [[1,3],[2,4],[5,6]]

x = np.array(arr)
print(x.T)
x.T.reshape(3,2)

In [ ]:
x.T.reshape(1,6).reshape(3,2)

In [ ]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
x
print(x.flatten())

In [ ]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print(v)
print(x[:,None])
print((x / v[:,None])[1][1])

In [ ]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])
print(p)
print(q+p)

In [ ]:
arr = [[ 0,  1,  2,  3],  [ 4,  5,  6,  7],   [ 8,  9, 10, 11],   [12, 13, 14, 15],   [16, 17, 18, 19]]

x = np.array(arr)

y = x[1:4]
print (y)
z = y[:, 2:]

print(z)


In [ ]:
import numpy as np
def ratio(marks_arr):
    # Complete the missing code
    x = np.array(marks_arr)
    distinction = x[x>=80] # Use masking to get the values
    first_div = x[(x<=60) & (x<80)] # Use masking to get the values

    distinction_count = len(distinction)
    first_div_count = len(first_div)

    ratio = distinction_count/first_div_count

    return round(ratio,2)
ratio([20, 35, 68, 52, 83, 70, 90, 95, 35, 99, 61])

In [ ]:
np.arange(22,71,2)

In [ ]:
np.arange(21,72,2)

In [ ]:
t = np.array([subset_votes, subset_costs]).T

In [ ]:
t

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
np.flipud([[1,2,3],[4,5,6],[7,8,9]]).T



In [ ]:
np.flipud([[1],[2]])

In [ ]:
matrix = np.array([[1],[2]])
transposed_matrix = matrix.transpose()
reversed_cols = np.fliplr(transposed_matrix)
print(transposed_matrix)

In [ ]:
np.rot90(matrix, k=-1)

In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)


In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])
g = a >= 10

In [ ]:
len(g)

In [ ]:
f = (a >= 60) & (a < 80)

In [ ]:
len(f)

In [ ]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])


In [ ]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q))

In [ ]:
a[1:0]

In [ ]:
np.fliplr([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])

In [ ]:
b = [[0, 1, 2],  [3, 4, 5],  [6, 7, 8]]
np.array(b)[:, ::-1]

In [ ]:
a

In [ ]:
np.arange(20,72,2)

In [ ]:
np.arange(21,72,2)

In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])

In [ ]:
arr

In [ ]:
arr.astype('float64')

In [ ]:
arr.astype(int)

In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])

In [ ]:
a

In [ ]:
x = np.transpose(a)
print(x)

In [ ]:
y = x.reshape(1,6)
print(y)

In [ ]:
arr = np.array([20, 35, 68, 82, 83, 70, 90])
print(arr)

In [ ]:
mask_distinction = arr >= 80
distinction_masked_array = arr[mask_distinction]
print(distinction_masked_array)

In [ ]:
mask_first_division = (arr >= 60) & (arr < 80)
first_divison_masked_array = arr[mask_first_division]
print(first_divison_masked_array)

In [ ]:
ratio = distinction_masked_array.size/first_divison_masked_array.size
print(ratio)

In [ ]:
import numpy as np
arr = [[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]]

In [ ]:
#get the rows 2nd to 4th
row_array = np.array(arr[1:4])
print(row_array)

In [ ]:
sliced_array = row_array[:, -3:]
print(sliced_array)

In [ ]:
sliced_array[::-1]

In [ ]:
arr = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])
print(arr)

In [ ]:
arr[:, ::-1]

In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

In [ ]:
def rotate_img(mat):
  transposed = mat.transpose()
  print(transposed[::-1])
  print(transposed[:, ::-1])
  return (mat.transpose())[:, ::-1]

In [ ]:
import numpy as np
size = int(input("Enter size of matrix: "))

In [ ]:
matrix = []
for i in range(size):
    row = list(map(int, input().split()))
    matrix.append(row)

mat = np.array(matrix)

print(mat)

In [ ]:
rotate_img(mat)

In [ ]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
print(x)

In [ ]:
v = np.array([200,300,400])

In [ ]:
print(v[:, None])

In [ ]:
x = np.array([[1,200,2],[300,300,300],[400,4,400]])
print(x)

In [ ]:
print(x[:, ::-1])
print(x[::-1])

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])


In [ ]:
a[:,[0]]

In [ ]:
np.sum(a, axis=1)


In [ ]:
np.where(a > 5)

In [ ]:
help(a.reshape(1, 9))

In [ ]:
np.sort(a, axis=0)

In [ ]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([1,2,3])
a1+a2

In [ ]:
def discouts(rating , costs):
  if(rating >= 4.0):
    return 0.9 * costs
  else:
    return costs
dvectorized = np.vectorize(discouts)
dvectorized(6 , 78)

In [ ]:
np.argsort(a)
x = np.array([0,1,2])
a[x]

In [ ]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [ ]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)


In [ ]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

In [ ]:
np.broadcast_to(arr1, arr.shape)

In [ ]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

In [ ]:
np.broadcast_to(arr1, arr.shape)

In [ ]:
x = np.ones((1,2))

np.broadcast_to(x, (3,2))

In [ ]:
arr = np.array([[1, 2], [3, 4]])

In [ ]:
pad_top = 1
pad_value=0
top_padding = np.full((pad_top, arr.shape[1]), pad_value)
top_padding

In [ ]:
x = np.vstack((top_padding, arr, top_padding ))

left_padding = np.full((x.shape[0], 1), 0)
left_padding

np.hstack((left_padding, x, left_padding))

In [ ]:
arrayToPad = np.array([[1,2],[3,4],[5,6]])

np.pad(arrayToPad, (1,1), 'constant', constant_values=(0, 0))

In [ ]:
help(np.pad)

np.pad(arr,  )

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])

help(np.hsplit)

x = np.vsplit(data, [2,3])
print(x)
y = np.vstack(x[0:len(x)-1])

np.vstack((x[-1], y))


In [3]:
birds = ['parrot', 'owl', 'macaw', 'macaw', 'owl', 'owl', 'macaw', 'macaw', 'sparrow', 'owl', 'sparrow', 'parrot', 'macaw', 'peacock', 'sparrow', 'macaw', 'peacock', 'owl', 'owl', 'parrot']
age = [8, 1, 12, 13, 13, 8, 11, 7, 6, 1, 7, 4, 12, 6, 1, 8, 14, 13, 14, 1]

In [4]:
np.array([3,6])

array([3, 6])

In [5]:
x = np.argsort(age)

# birds[x]
x

array([ 9, 14, 19,  1, 11, 13,  8,  7, 10, 15,  0,  5,  6,  2, 12,  4, 17,
        3, 16, 18])

In [6]:
a = np.array(birds)
b = np.array(age)
y = np.sort(b)
argsort = np.argsort(b)

print(a, '\n\n', argsort, '\n\n', a[argsort], '\n\n', np.take(a, argsort), '\n\n', a[argsort] == np.take(a, argsort))

['parrot' 'owl' 'macaw' 'macaw' 'owl' 'owl' 'macaw' 'macaw' 'sparrow'
 'owl' 'sparrow' 'parrot' 'macaw' 'peacock' 'sparrow' 'macaw' 'peacock'
 'owl' 'owl' 'parrot'] 

 [ 9 14 19  1 11 13  8  7 10 15  0  5  6  2 12  4 17  3 16 18] 

 ['owl' 'sparrow' 'parrot' 'owl' 'parrot' 'peacock' 'sparrow' 'macaw'
 'sparrow' 'macaw' 'parrot' 'owl' 'macaw' 'macaw' 'macaw' 'owl' 'owl'
 'macaw' 'peacock' 'owl'] 

 ['owl' 'sparrow' 'parrot' 'owl' 'parrot' 'peacock' 'sparrow' 'macaw'
 'sparrow' 'macaw' 'parrot' 'owl' 'macaw' 'macaw' 'macaw' 'owl' 'owl'
 'macaw' 'peacock' 'owl'] 

 [ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


In [ ]:
x = np.ones((5,5))
x[1:-1, 1:-1] = 0
x

In [ ]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))


In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
arr


In [ ]:
# np.hstack((arr, arr[:, [0]])).shape

np.hstack((arr, arr[:, [0]])).shape

In [ ]:
= (3, 4)

In [ ]:
np.hstack((arr, arr[:, [0]])).shape

In [ ]:
np.hstack((arr, arr[:, [0]])).shape

In [ ]:
arr1 = np.array([1,2,3,6,3,2])
arr2 = np.array([4,2,1,3,3,2])
arr3 = np.zeros(len(arr1))

In [ ]:
for i in range(len(arr1)):
    arr3[i] = arr1[i] * arr2[i]

print(arr3)

In [ ]:
a = np.arange(10,22).reshape((3, 4))

In [ ]:
a


In [ ]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [ ]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

In [ ]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

In [ ]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

In [ ]:
arr= [ 1,2,3,4,5]


In [ ]:
import numpy



In [ ]:
narr =  numpy.array(arr)


In [ ]:
narr

In [ ]:
narr *10


In [ ]:
numpy.arange(22,71,2)


In [ ]:
numpy.flip(narr)


In [ ]:
arr = np.array([[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]])

In [ ]:
import numpy as np


In [ ]:
arr = np.array([[1, 4, 7],
                [2, 5, 8],
                [3, 6, 9]])

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])



In [ ]:
arr.T[::-1]

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
arr.T

In [ ]:
arr[::-1]

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
arr

In [ ]:
arr[::-1]

In [ ]:
arr.T

In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])


In [ ]:
x = np.transpose(a)


In [ ]:
x

In [ ]:
x.reshape(3,2)


In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)

In [ ]:
marks = np.array([20, 35, 68, 82, 83, 70, 90])
print(np.sum(marks >= 80))

In [ ]:
marks

In [ ]:
marks >= 80

In [ ]:
print( marks[marks >= 80])

In [ ]:
import numpy as np
c = np.array([[1,100], [2,200], [3,300]])
c

In [ ]:
d = c.reshape(2,-1)
d

In [ ]:
e = c.reshape(-1,2)
e

In [ ]:
cost = np.array([100, 200, 150, 300, 160])
np.where(cost>180)

In [ ]:
help(np.sort)

In [ ]:
a = np.array([[1,4],[3,1]])
a

In [ ]:
np.sort(a)

In [ ]:
import numpy as np
help(np.hstack)

In [ ]:
birds = ['spoonbills', 'plovers', 'humming']
age = [5.5, 6.0, 3.5]

In [ ]:
sorted_age_index = np.argsort(age)
sorted_age_index

In [ ]:
sorted = np.argsort(sorted_age_index)
sorted

In [ ]:
arr1 = np.array([1,2,3,6,3,2])
arr2 = np.array([4,2,1,3,3,2])
arr3 = np.zeros(len(arr1))
arr1.shape, arr2.shape, arr3, arr3.shape

In [ ]:
arr = np.array([[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
arr, arr.shape

In [ ]:
arr[1,:,:]

In [ ]:
a = np.arange(10,22).reshape((3, 4))
print(a.shape)

In [ ]:
b = np.arange(2)
b.shape

In [ ]:
birds = ['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']
age = [6, 1, 6, 5, 7, 6, 0, 9, 0, 7]

In [ ]:
indexed_sorted_age = np.argsort(age)
indexed_sorted_age

In [ ]:
max_index = np.argmax(age)
max_index

In [ ]:
birds[7]

In [ ]:
arr = np.array([[0, 1, 2, 3, 100],
 [4, 5, 6, 7, 200],
 [8, 9, 10, 11, 300],
 [12, 13, 14, 15, 400],
 [16, 17, 18, 19, 500],
 [20, 21, 22, 23, 600]])
arr.shape

In [ ]:
subarray1 = arr[:, :2]
subarray1

In [ ]:
subarray2 = arr[:, 2]
subarray2.reshape(-1, 1)

In [ ]:
subarray3 = arr[:, 3:]
subarray3

In [ ]:
subarrays = [subarray1, subarray2, subarray3]
subarrays

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,1,1])
a+b

In [ ]:
help(np.flip)

In [ ]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr

In [ ]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

In [ ]:
help(np.hsplit)

In [ ]:
help(np.flip)

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
data

In [ ]:
arr.hsplit()

In [ ]:
array3D = np.array([[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
print(array3D)

In [ ]:
array3D[1, :, :]

In [ ]:
a = np.arange(10,22).reshape((3, 4))
print(a)

In [ ]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

arr1 = np.array([[2,2,2,2]])
arr2 = np.array([[2],[2],[2],[2]])
arr3 = 2

def func(x, y):
    return x * y
vec = np.vectorize(func)
print(vec(arr,arr1), '\n\n', vec(arr,arr2), '\n\n', vec(arr,arr3))

In [ ]:
import numpy as np

# Rotate matrix by 90 degree
arr = np. array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
arr                   #[[7 4 1]
                      # [8 5 2]
                      # [9 6 3]]

In [ ]:
T = arr.transpose()
T

In [ ]:
T[:, ::-1]

In [ ]:
arr = np.array([0,1,2,3,4,5])
arr.shape

In [ ]:
firstElement= arr[0]
lastElement = arr[-1]
(firstElement, lastElement)

In [ ]:
arr = np.array([20, 35, 68, 82, 83, 70, 90])
arr.shape

In [ ]:
v = np.array([1,2,3,4])
v.shape

In [ ]:
v[:, None]

In [ ]:
import numpy as np


In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])
num_splits = 2

In [ ]:
data.shape[0]


In [ ]:
sections = [data[i * 4: (i + 1) * 4] for i in range(num_splits)]


In [ ]:
sections

In [ ]:
np.vsplit(data, 2)

In [ ]:
data2 = np.vsplit(data, 2)
arr = np.concatenate((data2[1], data2[0]))
arr

In [ ]:
arr1 = np.array([[6, 6, 4, 7, 9],
 [0, 2, 2, 9, 3],
 [6, 0, 2, 5, 2],
 [2, 4, 3, 5, 5]])

arr2 = np.array([[8, 6, 6, 8, 3],
 [2, 7, 0, 3, 1],
 [3, 2, 1, 5, 2],
 [7, 0, 7, 6, 8],
 [1, 5, 6, 4, 5]])

# num_rows, num_cols = a.shape
arr1_rows, arr1_cols = arr1.shape
arr2_rows, arr2_cols = arr2.shape
print(arr1.shape, '\n\n', arr1_rows, arr1_cols, '\n\n')
print(arr2.shape, '\n\n', arr2_rows, arr2_cols)
if(arr1_cols != arr2_rows):
  print(-1)
else:
  print(0)

# print(arr1, '\n\n', arr2)
# mul = arr1 * arr2
# print(mul, '\n\n', mul[1:3, 2:4])

In [ ]:
import pandas as pd
import io

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1UViHcT4lKDsTfc97gBqIvds25uHe4b5e" -O sales.csv

In [ ]:
df = pd.read_csv("sales.csv")

In [ ]:
df.head(5)

In [ ]:
df.groupby(['Invoice'])['Description'].count().sort_values(ascending=False)

In [ ]:
  df[df['Invoice' == '537434']]

In [ ]:
highest_sales_index = df['Quantity'].max()
highest_sales_row = df[df['Quantity'] == highest_sales_index]
print(highest_sales_row)

In [ ]:
highest_sales_index = df['Quantity'].idxmax()
highest_sales_row = df.loc[highest_sales_index]
print(highest_sales_row)

In [ ]:
df['TotalAmount'] = df['Quantity'] * df['Price']
df_filtered = df[df['Quantity'] > 0]
highest_purchase = df_filtered.loc[df_filtered['TotalAmount'].idxmax()]
print(highest_purchase)

In [ ]:
data = """Name,Gender,Profession
Jim,M,Athelete
Carrier,F,Tech
Chris,M,Cricketer
Morris,M,Actor
"""


In [ ]:
df = pd.read_csv(io.StringIO(data))
df


In [ ]:
df['Name']
df.iloc[:2,:2]

In [ ]:
df.loc[:2,"Name":"Profession"]

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1Dtm4ZlXPqcwi8T98acWdyQueU0S8UTWj" -O titanic.csv

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic.head(4)

In [ ]:
titanic.T.drop_duplicates(keep="first")

In [ ]:
titanic.drop_duplicates(keep ="first")

In [ ]:
titanic.drop_duplicates(keep ="last")

In [ ]:
data = """date,name,amt
2020-01-01,Himanshu,100
2020-07-01,Robert,200
2020-08-01,Karle,400
2020-03-02,Rohan,150
2020-01-03,John,300
"""

In [ ]:
data


In [ ]:
df3 = pd.read_csv(io.StringIO(data))

In [ ]:
df3

In [ ]:
a = df3.loc[1:2]
a[["name","amt"]]

In [ ]:
data = """Country,Year,Population,Continent
Afghanistan,1952,8425333.0,Asia
Australia,1957,9712569.0,Oceania
Brazil,1962,76039390.0,Americas
China,1957,637408000.0,Asia
France,1957,44310863.0,Europe
India,1952,37200000.0,Asia
United States,1957,171984000.0,Americas
"""

In [ ]:
df4 = pd.read_csv(io.StringIO(data))
df4

In [ ]:
import pandas as pd

data2 = {
    'Country': ['Afghanistan', 'Australia', 'Brazil', 'China', 'France', 'India', 'United States'],
    'Year':  [1952, 1957, 1962, 1957, 1957, 1952, 1957],
    'Population':  [8425333.0, 9712569.0, 76039390.0, 637408000.0, 44310863.0, 372000000.0,  171984000.0],
    'Continent':  ['Asia', 'Oceania', 'Americas', 'Asia', 'Europe', 'Asia', 'Americas']
}

df6 = pd.DataFrame(data2)
df6

In [ ]:
df_filtered = df6[df6['Population'] > 10000000]
df_sorted = df_filtered.sort_values(by=['Year','Population'], ascending=[True, True])
df_sorted.reset_index(drop = True)

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1UcWItyfVGL-mPlnR002bDRx_rdkSbgGq" -O mtcars.csv

In [ ]:
df = pd.read_csv("mtcars.csv")

In [ ]:
df_explicit = df.set_index("model")


In [ ]:
df_explicit.iloc[1:5, 3:5]

In [ ]:
import pandas as pd

data = {
    'name': ['Bruno', 'Bruno', 'Harry', 'Selena', 'Weeknd'],
    'gender': ['M', 'M', 'M', 'F', 'M'],
    'income': ['low', 'low', 'medium', 'medium', 'medium']
}

df = pd.DataFrame(data)

In [ ]:
medium_income = df[df['income'] == 'medium']
medium_income_count = len(medium_income)
result = medium_income_count/len(df)*100
print(result)


In [ ]:
for x in df.columns:
    print(x)
    if df[x].nunique()==1:
        print("true")
        df.drop(x, axis=1, inplace=True)


In [ ]:
data = {'name':["Sam","Roma","Mark"], "profession":['dev','mle','Data scientist'],"gender":['male','female','male'], "age":[21,20,25],"review":['No comments','hardworker','need improvement'],"rating":[10,5,7]}

In [ ]:
df = pd.DataFrame(data)
medium_income = df[df['rating'] >= 6][['profession','gender','age']]
medium_income

In [ ]:
import pandas as pd

data = {
    'name': ['Mark', 'Ramilla', 'Deb', 'Laxman'],
    'profession': ['dev', 'mle', 'mle', 'hr'],
    'gender': ['male', 'female', 'male', 'male'],
    'age': [21, 20, 30, 27],
    'review': ['need improvement', 'Can be improved', 'Scope of improvement', 'Great'],
    'rating': [10, 5, 7, 9]
}

df = pd.DataFrame(data)
df_new = df[df['gender'] == 'male' ]
df_new = df_new[(df_new['age'] >= 23) & (df_new['age'] <= 30)][['name']]
df_new

In [ ]:
import pandas as pd
df = pd.DataFrame({'City\tState': ["Kolkata\tWest Bengal", "Chennai\tTamil Nadu", "Hyderabad\tTelengana", "Bangalore\tKarnataka"]})
#df[['City', 'State']] = df['City\tState'].str.split('\\t', expand=True)
#df[['City', 'State']]

df_new = df['City\tState'].str.split('\\t', expand=True)
df_new.columns = ['City', 'State']
df_new


### **Assignment - 03/12/2025**

In [ ]:
df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])
df

In [ ]:
df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})

In [ ]:
data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}
df = pd.DataFrame(data)
df

In [ ]:
grouped_df = df.groupby(by='gender')['income'].mean()
grouped_df

In [ ]:
df_new = pd.DataFrame(grouped_df)
type(df_new)

In [ ]:
import pandas as pd

In [ ]:
def solve(reg_id, reg_dates):
    res_df = pd.DataFrame(zip(reg_id, reg_dates), columns=["RID", "RDate"])

In [ ]:
import pandas as pd
df = pd.DataFrame({'RID': [56, 92, 29, 93, 55, 32], 'RDate': pd.to_datetime(['2021-01-01', '2021-02-12', '2021-04-16', '2021-01-22', '2021-01-15', '2021-02-26'])})
df

In [ ]:
df['RMonth'] = df['RDate'].dt.month
df['RYear'] = df['RDate'].dt.year
df['RDay'] = df['RDate'].dt.day
df

In [ ]:
df = pd.read_csv('/sales (1).csv')
# df.head(5)
df.shape

In [ ]:
products = ['WORLD WAR 2 GLIDERS ASSTD DESIGNS', 'BLACK AND WHITE PAISLEY FLOWER MUG', 'PACK OF 60 PINK PAISLEY CAKE CASES', 'WHITE HANGING HEART T-LIGHT HOLDER']
df[df['Description'].isin(products)].groupby('Description')['Description'].count().sort_values(ascending=False)

In [ ]:
df['Description'].value_counts().head(10)

In [ ]:
df[df['Description'].str.contains('WORLD WAR', case=True, na=False)]['Description'].value_counts()

In [ ]:
df.isna().sum()

In [ ]:
df['Description'].fillna('')

In [ ]:
products = ['WORLD WAR 2 GLIDERS ASSTD DESIGNS', 'BLACK AND WHITE PAISLEY FLOWER MUG', 'PACK OF 60 PINK PAISLEY CAKE CASES', 'WHITE HANGING HEART T-LIGHT HOLDER']
df[df['Description'].isin(products)].groupby('Description')['Description'].count().sort_values(ascending=False)

In [ ]:
import pandas as pd

data = {
    'ord_no': [70001, 70009, 70002, 70004, 70007, 70005, 70008, 70010, 70003, 70012, 70011, 70013],
    'purch_amt': [150.50, 270.65, 65.26, 110.50, 948.50, 2400.60, 5760.00, 1983.43, 2480.40, 250.45, 75.29, 3045.60],
    'ord_date': ['2012-10-05', '2012-09-10', '2012-10-05', '2012-08-17', '2012-09-10', '2012-07-27', '2012-09-10', '2012-10-10', '2012-10-10', '2012-06-27', '2012-08-17', '2012-04-25'],
    'customer_id': [3005, 3001, 3002, 3009, 3005, 3007, 3002, 3004, 3009, 3008, 3003, 3002],
    'salesman_id': [5002, 5005, 5001, 5003, 5002, 5001, 5001, 5006, 5003, 5002, 5007, 5001]
}

df = pd.DataFrame(data)
df

In [ ]:
result = df.groupby(by=['salesman_id', 'customer_id'])['ord_no'].count()
df_new = result.reset_index(name='ord_no')
df_new

In [ ]:
type(result)

In [ ]:
df_count = df.groupby(by=['salesman_id', 'customer_id'])['ord_no'].size()
df_count.reset_index()

In [ ]:
result = df.groupby(by=['salesman_id', 'customer_id'])['ord_no'].count()
result
# result = df.groupby(by=['salesman_id', 'customer_id'])['ord_no'].size()
result.reset_index()

In [ ]:
df_count

In [ ]:
import pandas as pd

data = {
    'pickup': pd.to_datetime([
        '2023-01-01 04:30:00',  # morning
        '2023-01-01 14:30:00',  # afternoon
        '2023-01-01 15:45:00',  # afternoon
        '2023-01-01 16:20:00',  # afternoon
        '2023-01-01 22:15:00'   # night
    ]),
    'dropoff': pd.to_datetime([
        '2023-01-01 05:00:00',
        '2023-01-01 15:00:00',
        '2023-01-01 16:15:00',
        '2023-01-01 17:00:00',
        '2023-01-01 23:00:00'
    ]),
    'passenger_count': [1, 2, 3, 2, 1],
    'trip_distance': [2.5, 3.0, 4.5, 2.8, 3.2],
    'fare_amount': [15.5, 20.0, 25.5, 18.0, 22.0]
}

df1 = pd.DataFrame(data)
df1

In [ ]:
hour = df['pickup'].dt.hour
hour

In [ ]:
conditions = [
    (0 <= hour) & (hour < 6),
    (6 <= hour) & (hour < 12),
    (12 <= hour) & (hour < 18),
    (18 <= hour) & (hour < 24)
]
conditions

In [ ]:
values = ['morning', 'day', 'afternoon', 'night']
values

In [ ]:
import numpy as np

df['time_of_day'] = pd.Categorical(np.select(conditions, values), categories=values)
print((df['time_of_day'].value_counts(ascending=False, dropna=False)).name == 'pickup')

In [ ]:
import pandas as pd

data = {
    'name': ['Jim', 'Clarke', 'Kent', 'Mark'],
    'username': ['itsjimhere', 'clark002', 'itskentment', 'markyoumustknow'],
    'userid': [20, 10, 86, 21]
}

df2 = pd.DataFrame(data)
df2

In [ ]:
def check(name, username):
  return name.lower() in username

In [ ]:
check('nupur', 'nupur0110')

In [ ]:
df.apply(lambda x: check(x['name'], x['username']), axis=1)

In [ ]:
df[~(df.apply(lambda x:check(x['name'],x['username']), axis=1))]['userid']

In [ ]:
df3 = pd.concat([df1, df2], axis=0)

In [ ]:
df3

In [ ]:
import pandas as pd

dict1 = {
  "A": ['1', '2', '3', '4'],
  "B": ['11', '22', '33', '44'],
  "C": ['111', '222', '333', '444'],
}
df1 = pd.DataFrame(dict1, index=["first", "second", "third", "fourth"])

dict2 = {
  "D": ["a", "b", "c", "d"],
  "E": ["aa", "bb", "cc", "dd"],
  "F": ["aaa", "bbb", "ccc", "ddd"],
}
df2 = pd.DataFrame(dict2, index=["fourth", "fifth", "sixth", "seventh"])
df1

In [ ]:
df2

In [ ]:
df3 = pd.concat([df1, df2])
df3

In [ ]:
#Block a
df4=df3.drop(["fourth"])
df4

In [ ]:
df3.loc['fourth','A']*2

In [ ]:
#Block b
df4 = df3.reset_index().drop_duplicates(subset='index', keep='last')
df4 = df4.set_index('index').sort_index()
df4

In [ ]:
df = pd.DataFrame({'name':["Ram","Shyam","Mukesh","Suresh"],'age':[10,18,60,50]})
df

In [ ]:
def to_category(df):
  if(df.age<18):
    return "kid"
  if((df.age >=18) & (df.age<=50)):
    return "adult"
  if(df.age>50):
    return "senior"

In [ ]:
df_new = df.apply(lambda x: to_category(x), axis=1)
df_new

In [ ]:
df_new1 = pd.concat([df['name'], df_new], axis=1)
df_new1.columns = ['name', 'age']
df_new1

In [ ]:
import pandas as pd

data = {
    'Country': ['USA', 'Japan', 'France', 'Germany', 'Canada'],
    '2015': [78.5, 83.2, 82.1, 80.7, 81.9],
    '2016': [78.7, 83.4, 82.3, 80.9, 82.1],
    '2017': [78.9, 83.6, 82.5, 81.1, 82.3],
    '2018': [79.1, 83.8, 82.7, 81.3, 82.5],
    '2019': [79.3, 84.0, 82.9, 81.5, 82.7]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
df.drop('Country', axis=1, inplace=True)
df

In [ ]:
pd.melt()

In [ ]:
import pandas as pd

data = {
    'roll_no': [1, 2, 1, 3, 1, 3, 3, 3, 2, 2, 1, 2],
    'subject': ['NN', 'DL', 'ML', 'Prob', 'DL', 'ML', 'DL', 'NN', 'NN', 'Prob', 'Prob', 'ML'],
    'marks': [97, 63, 63, 71, 64, 90, 66, 46, 74, 62, 94, 67]
}

df = pd.DataFrame(data)
df

In [ ]:
df_new = df.groupby('subject')['marks'].max()
df_new

In [ ]:
df_new.reset_index()

In [ ]:
result = pd.merge(df, df_new, how='right', on=['marks', 'subject'])
result[['subject', 'marks', 'roll_no']]

In [ ]:
import pandas as pd

sales_data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'Region': ['East', 'West', 'East', 'West'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 200, 150, 250]
}

df = pd.DataFrame(sales_data)

In [ ]:
df

In [ ]:
def generate_pivot_table(df):
  pd.pivot_table(df, values=)

In [ ]:
df.fillna(0)
df.groupby('Region')['Sales'].sum().sort_values()

1. Create a pivot table with 'Region' as the index and the sum of 'Sales' as the values.
2. Handle missing values, filling them with zeros.
3. Sort the resulting pivot table rows and columns alphabetically.

In [ ]:
df.pivot_table(values='Sales', index='Region', fill_value=0, aggfunc='sum').sort_values(by=['Region', 'Sales'])

In [ ]:
import pandas as pd

data = {
    'Country': ['USA', 'Japan', 'France', 'Germany', 'Canada'],
    '2015': [78.5, 83.2, 82.1, 80.7, 81.9],
    '2016': [78.7, 83.4, 82.3, 80.9, 82.1],
    '2017': [78.9, 83.6, 82.5, 81.1, 82.3],
    '2018': [79.1, 83.8, 82.7, 81.3, 82.5],
    '2019': [79.3, 84.0, 82.9, 81.5, 82.7]
}

df = pd.DataFrame(data)
df

In [ ]:
df_new = pd.melt(df.drop('Country', axis=1), value_name='Life_Expectancy', var_name='Year')
# df_new.set_index('Year')
df_new

In [ ]:
result = df_new.groupby('Year').agg({'Life_Expectancy': 'mean'}).sort_values(by='Year')
pd.DataFrame(result)

In [ ]:
# Using agg() with multiple operations - returns DataFrame
result2 = df_new.groupby('Year').agg({'Life_Expectancy': 'mean'})
print("DataFrame output:", type(result2))

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1UViHcT4lKDsTfc97gBqIvds25uHe4b5e" -O sales.csv

In [ ]:
import pandas as pd
sales = pd.read_csv("sales.csv")
grouped_counts = sales.groupby('Description')['Quantity'].sum()
grouped_counts.sort_values(ascending=False).head(1)


In [ ]:
data = {
    'ord_no': [70001, 70009, 70002, 70004, 70007, 70005, 70008, 70010, 70003, 70012, 70011, 70013],
    'purch_amt': [150.50, 270.65, 65.26, 110.50, 948.50, 2400.60, 5760.00, 1983.43, 2480.40, 250.45, 75.29, 3045.60],
    'ord_date': ['2012-10-05', '2012-09-10', '2012-10-05', '2012-08-17', '2012-09-10', '2012-07-27', '2012-09-10', '2012-10-10', '2012-10-10', '2012-06-27', '2012-08-17', '2012-04-25'],
    'customer_id': [3005, 3001, 3002, 3009, 3005, 3007, 3002, 3004, 3009, 3008, 3003, 3002],
    'salesman_id': [5002, 5005, 5001, 5003, 5002, 5001, 5001, 5006, 5003, 5002, 5007, 5001]
}

df = pd.DataFrame(data)
df.groupby(['salesman_id', 'customer_id'], as_index = False)['ord_no'].count()

In [ ]:
import pandas as pd

data1 = {
    'cust_id': [101, 102, 103, 104],
    'name': ['rick', 'morty', 'pickle', 'jerry']
}

data2 = {
    'order_id': ['OR1', 'OR3', 'OR23', 'OR42'],
    'cust_id': [102, 105, 101, 102],
    'amount': [1200, 650, 120, 989]
}
customer = pd.DataFrame(data1)
orders = pd.DataFrame(data2)

merged_df = pd.merge(customer, orders, how='left', on='cust_id')
merged_df.groupby('name')['amount'].sum().loc["morty"]


In [ ]:
import pandas as pd

data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}

df = pd.DataFrame(data)
result = df.groupby('gender', as_index=False)['income'].mean()
result.set_index('gender', inplace = True)
result

In [ ]:
import pandas as pd

data = {
    'pickup': pd.to_datetime(['2019-03-23 20:21:09', '2019-03-04 16:11:55', '2019-03-27 17:53:01', '2019-03-10 01:23:59', '2019-03-30 13:27:42']),
    'dropoff': pd.to_datetime(['2019-03-23 20:27:24', '2019-03-04 16:19:00', '2019-03-27 18:00:25', '2019-03-10 01:49:51', '2019-03-30 13:37:14']),
    'passengers': [1, 1, 1, 1, 3],
    'distance': [1.60, 0.79, 1.37, 7.70, 2.16]
}
df = pd.DataFrame(data)
df

def sort_and_sum(group):
    sorted_group = group.sort_values(by='pickup',ascending=False)
    return pd.Series({'pickup': sorted_group['pickup'].max()})

def calculate_time_of_day_to_date(date_value):
    """Calculates the time of day based on the to_date time."""
    time_hour = date_value.hour

    if 0 <= time_hour <= 6:
        return 'morning'
    elif 6 < time_hour <= 12:
        return 'day'
    elif 12 < time_hour <= 18:
        return 'afternoon'
    else:
        return 'night'

df2 = pd.DataFrame({'time_of_day': ['morning', 'day', 'afternoon', 'night'], 'passengers': [0, 0, 0, 0]})
df['time_of_day'] = df['pickup'].apply(calculate_time_of_day_to_date)
#df = df.rename(columns={ 'time_of_day': 'a'})
df3 = pd.concat([df, df2], ignore_index=True)
selected_columns = ['time_of_day', 'passengers']  # List of columns to select
new_df = df3[selected_columns]
df6 = new_df.rename(columns={ 'passengers': 'pickup'})
sorted_df = df6.sort_values('pickup', ascending=False)
sorted_df = sorted_df.groupby('time_of_day').apply(sort_and_sum)
sorted_df = sorted_df.sort_values(by='pickup', ascending=False)
sorted_df = sorted_df.groupby('time_of_day')['pickup'].max()
sorted_df

In [ ]:
import pandas as pd

def calculate_time_of_day_to_date(date_value):
    """Calculates the time of day based on the to_date time."""
    time_hour = date_value.hour

    if 0 <= time_hour < 6:
        return 'morning'
    elif 6 <= time_hour < 12:
        return 'day'
    elif 12 <= time_hour <= 18:
        return 'afternoon'
    else:
        return 'night'

def timeOfDay(df):
    df2 = pd.DataFrame({'time_of_day': ['morning', 'day', 'afternoon', 'night'], 'passengers': [0, 0, 0, 0]})
    df['time_of_day'] = df['pickup'].apply(calculate_time_of_day_to_date)
    df3 = pd.concat([df, df2], ignore_index=True)
    selected_columns = ['time_of_day', 'passengers']  # List of columns to select
    new_df = df3[selected_columns]
    df6 = new_df.rename(columns={ 'passengers': 'pickup'})
    df4 = df6.groupby(['time_of_day'])['pickup'].max()
    result = pd.DataFrame(df4).sort_values(by='pickup', ascending=False)
    return result.squeeze()

df = pd.DataFrame([
    ['2019-03-23 10:21:09', '2019-03-23 10:27:24', 1, 1.6],
     ['2019-03-04 16:11:55', '2019-03-04 16:19:00', 1, 0.79],
      ['2019-03-27 17:53:01', '2019-03-27 18:00:25', 1, 1.37],
       ['2019-03-10 01:23:59', '2019-03-10 01:49:51', 1, 7.70],
        ['2019-03-30 13:27:42', '2019-03-30 13:37:14', 3, 2.16]],
          columns = ['pickup', 'dropoff', 'passengers', 'distance'])

df = pd.DataFrame(data)
timeOfDay(df)



In [ ]:
import pandas as pd

data = {
    'pickup': pd.to_datetime(['2019-03-23 20:21:09', '2019-03-04 16:11:55', '2019-03-27 17:53:01', '2019-03-10 01:23:59', '2019-03-30 13:27:42']),
    'dropoff': pd.to_datetime(['2019-03-23 20:27:24', '2019-03-04 16:19:00', '2019-03-27 18:00:25', '2019-03-10 01:49:51', '2019-03-30 13:37:14']),
    'passengers': [1, 1, 1, 1, 3],
    'distance': [1.60, 0.79, 1.37, 7.70, 2.16]
}


def categorize_time_of_day(pickup_time):
    """Categorizes pickup time into time of day labels."""
    hour = pickup_time.hour
    if 0 <= hour < 6:
        return 'morning'
    elif 6 <= hour < 12:
        return 'day'
    elif 12 <= hour < 18:
        return 'afternoon'
    else:
        return 'night'

def pickups_by_time_of_day(df):
    """Calculates the number of pickups for each time of day.

    Args:
        df: Pandas DataFrame with a 'pickup_time' column (datetime).

    Returns:
        Pandas Series containing the number of pickups for each time of day,
        sorted in descending order.
    """
    df3 = pd.concat([df, df2], ignore_index=True)

    df['time_of_day'] = df['pickup'].apply(categorize_time_of_day)
    return df['time_of_day'].value_counts().sort_values(ascending=False)

df = pd.DataFrame(data)

# Calculate and print the result
result = pickups_by_time_of_day(df)
print(result)
df2 = pd.DataFrame({'time_of_day': ['morning', 'day', 'afternoon', 'night'], 'pickup': [0, 0, 0, 0]})
print(df2)

In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'index': ['first', 'second', 'third', 'fourth'],
    'A': [1, 2, 3, 4],
    'B': [11, 22, 33, 44],
    'C': [111, 222, 333, 444]
})

df2 = pd.DataFrame({
    'index': ['fourth', 'fifth', 'sixth', 'seventh'],
    'D': ['a', 'b', 'c', 'd'],
    'F': ['aa', 'bb', 'cc', 'dd'],
    'E': ['aaa', 'bbb', 'ccc', 'ddd']
})

df1 = df1.set_index('index')
df2 = df2.set_index('index')

df3=pd.concat([df1,df2])
df3

In [ ]:
import pandas as pd

data = {'id': ['A1', 'A2', 'A3', 'A4'],
        'col1': [10, 20, 30, 40],
        'col2': ['X', 'Y', 'Z', 'W']}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Set 'id' column as the index
df = df.set_index('id')
print("\nDataFrame with Custom Index:\n", df)

#Inplace setting of the index.
df_inplace = pd.DataFrame(data)
df_inplace.set_index('id', inplace = True)
print("\nDataFrame with Inplace Custom Index:\n", df_inplace)

In [ ]:
df1

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'name': ['Jack','Ryan','Chris','Sam'], 'rank': [1, 2, 3, 4]})



df2 = pd.DataFrame({'name': ['Ryan', 'Sam', 'Chris', 'Jack'], 'rank': [3, 1, 4, 2]})

In [ ]:
df1

In [ ]:
df2

In [ ]:
print(pd.merge(df1, df2, on="name"))

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]
birds_arr = np.array(birds)
birds_arr

In [ ]:
age_arr = np.array(age)
age_arr

In [ ]:
import numpy as np

In [ ]:
mask = birds_arr == 'Cranes'
mask

In [ ]:
crane_ages = age_arr[mask]

In [ ]:
mean_age = crane_ages.mean()
mean_age

In [ ]:
mean_age.round(2)

In [ ]:
arr = np.array([10, 12, 14, 16, 18])
k = 4
arr

In [ ]:
mask = (arr % 2 == 0) & (arr > k)
mask

In [ ]:
np.all(mask)

In [ ]:
df = pd.read_csv('/mtcars.csv')
df.head(5)

In [ ]:
df.iloc[:,3].head(5)

In [ ]:
df.loc[:,'disp'].head(5)

In [ ]:
import pandas as pd

data = {
    'cust_id': [101, 102, 103, 104],
    'name': ['rick', 'morty', 'pickle', 'jerry']
}

customer = pd.DataFrame(data)
data = {
    'order_id': ['OR1', 'OR3', 'OR23', 'OR42'],
    'cust_id': [102, 105, 101, 102],
    'amount': [1200, 650, 120, 989]
}

orders = pd.DataFrame(data)
merged_df = customer.set_index('cust_id').join(orders.set_index('cust_id')).reset_index()
print(merged_df[merged_df['name']=='morty']['amount'].sum())

In [ ]:
import pandas as pd

data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000.0, 28000.0, 25000.0, 44000.0]
}

df = pd.DataFrame(data)
print(df[['gender','income']].groupby("gender").mean())

In [ ]:
df=pd.DataFrame([['Canada', 70.6, 78.3, 80.2, 82.3, 81.4, 80.3], ['France', 71.8, 74.7, 79.32, 77.2, 80.0, 81.2], ['Germany', 74.8, 74.7, 77.32, 77.2, 80.0, 81.2], ['Japan', 74.9, 74.7, 77.32, 77.8, 82.0, 81.2], ['Korea', 74.1, 74.7, 77.32, 77.2, 80.0, 83.2]], columns = ['Country', 2000, 2001, 2002, 2003, 2004, 2005])

In [ ]:
print(df.T)

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_rel

def analyze_ratings(seed_value):
    """
    Analyzes restaurant ratings to determine if there is a significant increase post-revamp.

    Return:
        - Mean difference between ratings (rounded to 3 decimals).
        - p-value from hypothesis test (rounded to 2 decimals).
        - Conclusion: "Significant Increase" if p < 0.05, else "No Significant Increase".
    """

    # Step 1: Generate synthetic data (Ratings for 30 customers)
    np.random.seed(seed_value)
    before_ratings = np.random.uniform(2.5, 4.5, 30)  # Ratings before menu revamp
    after_ratings = before_ratings + np.random.uniform(0, 1, 30)  # Ratings after revamp

    # Step 2: Create a Pandas DataFrame
    df = pd.DataFrame({
        "Rating_Before": before_ratings,
        "Rating_After": after_ratings
    })

    # Step 3: Compute the mean rating difference using NumPy
    mean_difference=round(np.mean(df.iloc[:,0])-np.mean(df.iloc[:,1]),3)

    # Step 4: Perform a paired t-test using scipy.stats.ttest_rel
    p_value = round(ttest_rel(df["before_ratings"],df["after_ratings"]).pvalue, 2)

    # Step 5: Determine conclusion based on hypothesis test result
    conclusion = "Significant Increase" if p_value < 0.05 else  "No Significant Increase"

    # return the results as required
    return mean_difference, p_value, conclusion


In [ ]:
import scipy.stats as stats

# Data
cars = [19.9, 15.3, 2.2, 6.8, 34.2, 8.3, 12.0, 7.0, 9.5, 1.1]
buses = [1.8, 24.6, 7.2, 37.0, 7.2, 21.2, 6.5, 23.6]
trucks = [13.3, 23.0, 25.4, 15.3, 57.1, 14.5, 26.0]

# Perform one-way ANOVA
f_statistic, p_value = stats.f_oneway(cars, buses, trucks)

print(f"F-Statistic: {f_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Decision based on 93% confidence level (alpha = 0.07)
alpha = 0.07
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in mean miles driven.")
else:
    print("Fail to reject the null hypothesis: No significant difference in mean miles driven.")

In [ ]:
df

In [ ]:
df.sort_values('income', ascending=False, inplace=True)
df

In [ ]:
df=pd.DataFrame([['Canada', 70.6, 78.3, 80.2, 82.3, 81.4, 80.3], ['France', 71.8, 74.7, 79.32, 77.2, 80.0, 81.2], ['Germany', 74.8, 74.7, 77.32, 77.2, 80.0, 81.2], ['Japan', 74.9, 74.7, 77.32, 77.8, 82.0, 81.2], ['Korea', 74.1, 74.7, 77.32, 77.2, 80.0, 83.2]], columns = ['Country', 2000, 2001, 2002, 2003, 2004, 2005])
df.set_index('Country', inplace=True)
DF=df.T.mean(axis=1).to_frame(name="Life_Expectancy").sort_values(by="Life_Expectancy", ascending=False).iloc[:5]
DF.rename_axis("Year")

In [ ]:
import pandas as pd

data = {
    'roll_no': [1, 2, 1, 3, 1, 3, 3, 3, 2, 2, 1, 2],
    'subject': ['NN', 'DL', 'ML', 'Prob', 'DL', 'ML', 'DL', 'NN', 'NN', 'Prob', 'Prob', 'ML'],
    'marks': [97, 63, 63, 71, 64, 90, 66, 46, 74, 62, 94, 67]
}

df = pd.DataFrame(data)
max_marks = df.groupby(by="subject").max().reset_index()[["subject","marks"]]
max_marks.join(df[["roll_no","marks"]].set_index('marks'),on="marks",how='left')


In [ ]:
import numpy as np
from scipy.stats import norm
z=norm.cdf(0.5)
1-z

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'name': ['Jack','Ryan','Chris','Sam'],
'rank': [1, 2, 3, 4]})
df2 = pd.DataFrame({'name': ['Ryan', 'Sam', 'Chris', 'Jack'],
'rank': [3, 1, 4, 2]})

print(pd.merge(df1, df2, on="name"))

In [ ]:
import numpy as np
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
age[birds=="Cranes"].mean()


In [ ]:
import numpy as np
a=np.array([10, 12, 14, 16, 18])

k=4
b=a[(a%2==0)&(a>k)]
print(a.shape[0],b.shape[0])

In [ ]:
import pandas as pd

sales_data = {
    'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
    'Region': ['East', 'West', 'East', 'West'],
    'Product': ['A', 'B', 'A', 'B'],
    'Sales': [100, 200, 150, 250]
}

df = pd.DataFrame(data)

In [ ]:
import pandas as pd
reg_id=[56, 92, 29, 93, 55, 32]
reg_dates=[2021-01-01, 2021-02-12, 2021-04-16, 2021-01-22, 2021-01-15, 2021-02-26]
res_df = pd.DataFrame(zip(reg_id, reg_dates), columns=["RID", "RDate"])

In [ ]:
import seaborn as sns
import pandas as pd
categories = ['Electronics', 'Clothing', 'Electronics', 'Electronics', 'Clothing', 'Clothing', 'Electronics', 'Electronics', 'Clothing', 'Electronics', 'Clothing', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Electronics', 'Clothing', 'Clothing', 'Electronics', 'Electronics']
sources = ['Social Media', 'Email', 'TV Advertisement', 'Social Media', 'Email', 'TV Advertisement', 'Social Media', 'Email', 'TV Advertisement', 'Social Media', 'Email', 'TV Advertisement', 'Social Media', 'Email', 'TV Advertisement', 'Social Media', 'Email', 'TV Advertisement', 'Social Media', 'Email']
df = pd.DataFrame({'Category': categories, 'Marketing Source': sources})
# Your code below
# plot the countplot in cp
cp = sns.histplot(data=df, x='Marketing Source')


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

protein = [4, 3, 4, 4, 2, 2, 2, 3, 2, 3, 1, 6, 1, 3, 1, 2, 2, 1, 1, 3, 3, 2, 2, 2, 2, 1, 3, 3, 3, 1, 2, 1, 3, 3, 3, 1, 3, 1, 2, 3, 2, 4, 2, 4, 4, 4, 3, 2, 2, 3, 3, 3, 3, 3, 1, 2, 4, 5, 3, 3, 2, 1, 2, 2, 3, 3, 2, 6, 2, 2, 3, 3, 2, 1, 3, 3, 2]
x, y = np.unique(protein, return_counts=True)
fig = plt.figure()

#Create the bar plot
plt.bar(x, y, color = "g")

#Add the xlabel
plt.xlabel("Protein amount in grams")

#Add the ylabel
plt.ylabel("Number of cereals")
#Add the title
plt.title('Protein comparison')
fig.show()

In [ ]:
from scipy import stats
import math

In [ ]:
n = 5
mean = 1900
std = 100
H0 = 1800
alpha = 0.01

In [ ]:
SE = std/math.sqrt(n)
SE

In [ ]:
z = (1800-1900)/SE
z

In [ ]:
stats.norm.cdf(z)

In [ ]:
mean = 65
std = 2.5
n =20
mean_of_sample = 64.5
p = 0.05

In [ ]:
SE = std/math.sqrt(n)
SE

In [ ]:
z = (64.5-65)/SE
z

In [ ]:
stats.norm.cdf(z)  # Probability more means H0 not rejetced

In [ ]:
z_score = stats.norm.ppf(0.90)
z_score

In [ ]:
mean = 13270.42
std = 12110.01
n = 1338

In [ ]:
se = std/math.sqrt(n)
se

In [ ]:
z = (13000-mean)/se
z

In [ ]:
stats.norm.cdf(abs(z))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [19]:
z = np.linspace(-10, 10, num=100)

# Sigmoid function
sigmoid = 1 / (1 + np.exp(-z))

plt.figure(figsize=(10,6))
plt.plot(z, y)
plt.title("Sigmoid function")
plt.xlabel('z')
plt.ylabel('Sigmoid')
plt.grid(True)
plt.axvline()

NameError: name 'plt' is not defined

In [17]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7]
b = [32, 34, 25 ,64, 77, 71, 83]
A = np.column_stack((a, b))
print(A)

[[ 1 32]
 [ 2 34]
 [ 3 25]
 [ 4 64]
 [ 5 77]
 [ 6 71]
 [ 7 83]]


In [9]:

np.mean(A[:, 1])

np.float64(55.142857142857146)

In [10]:
np.mean(A[:, 0])

np.float64(4.0)

In [15]:
np.sum(A, axis = 0)

array([ 28, 386])

In [18]:
np.sum(A, axis = 1)

array([33, 36, 28, 68, 82, 77, 90])

axis 0 means vertical, axis 1, means horizontal